version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: >-
    msbuild /t:restore Wirehome.sln
    
    cd Wirehome.Configurator
    
    npm install
build:
  project: Wirehome.sln
  verbosity: minimal

test_script:
- cmd: dotnet vstest "%APPVEYOR_BUILD_FOLDER%\Wirehome.Tests\bin\Release\netcoreapp2.2\Wirehome.Tests.dll"
